baseURL = 'https://bagggage.github.io/'
languageCode = "en-us"
title = "@bag-dev-blog"
theme = "archie"
copyright = "Konstantin Pigulevskiy"

[params]
    mode="dark"
	customcss = ["css/index.css"]

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/bagggage"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 2

[[menu.main]]
name = "GitHub"
url = "https://github.com/bagggage"
weight = 3